Built the middle section
YKerroum/Portfolio pull request #2
Opened 2022-07-02 00:39 UTC by YKerroum

### Add Personnal sections

- Add Projects section.
- Add About section.
- Add Skills section.

2022-07-02 01:22 UTC, danielufeli requested changes
Hi @YKerroum , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 01:22 UTC, danielufeli commented on index.html
> +					<p class="title-projects">My First Project</p>
- [ ] Kindly make all the project titles use a header tag `hx` for proper use of HTML semantics.

2022-07-02 01:22 UTC, danielufeli commented on index.html
> +				<div class="work-html">
- [ ] Kindly change the list of the project technologies to a list `ul` and for each of them, a `li`.

2022-07-02 02:32 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @YKerroum 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
-  Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 02:32 UTC, Bondok6 commented on index.html
> +			<h1 id="project-title">Projects</h1>
- [OPTIONAL] Great job using a heading tag here 💯, but I suggest using `<h2>,<h3>, etc...` instead of `<h1>`. to Follow best practices for HTML **Only Use H1 Elements Once Per Page for optimal SEO**. for more info, you can check this [Link](https://techstacker.com/seo-only-use-h1-elements-once-per-page/).

> Note: you used `<h1>` tag once here `<h1 class="name">I'm Youssef<br>Glad to see you!</h1>`, that's good because this is the main title 💯

2022-07-02 02:32 UTC, Bondok6 commented on index.html
> +					<button class="bouton-see background-blue" type="button">See this project <img class="union" src="./assets/images/Union.svg" alt="Union icon"></button>
- [OPTIONAL] According to the requirements, You should Implement the button interactions (enable, hover, etc.). Kindly, add the button interactions based on your Figma Design 👌.

![1](https://user-images.githubusercontent.com/45231276/176833382-1d1d826d-6c66-47ac-bec8-36427809918f.PNG)

![image](https://user-images.githubusercontent.com/45231276/176983437-5cf74f11-a162-45c9-96dc-89c9d981be1d.png)

> Note: you should do this on all buttons 👌

2022-07-02 13:57 UTC, YKerroum commented on index.html
> +			<h1 id="project-title">Projects</h1>
Thank you a lot for your suggestion.

2022-07-02 13:58 UTC, merged

2022-07-03 15:39 UTC, YKerroum commented on index.html
> +					<button class="bouton-see background-blue" type="button">See this project <img class="union" src="./assets/images/Union.svg" alt="Union icon"></button>
Thanks for the comment i will add it now.